            workflow_id: 'main.yml',  // 使用 main.yml 作为 workflow_id
            per_page: 1,
                      workflow_id: 'main.yml',  
>>>>>>>-HEAD
s.data.w            workflow_id: 'main.yml',  // 使用 main.yml 作为 workflow_id
>>>>>>>+main
].id);
          } else {
            core.setFailed('No previous successful workflow run found');
          }
      continue-on-error: true

    - name: Download artifacts - Session
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      uses: actions/download-    - name: Download artifacts
n_name
     - name: Download artifacts - Session
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      uses: actions/download-artifact@v4
      with:
        name: session_name
        path: .
        run-id: ${{ steps.get-previous-run-id.outputs.run_id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Download artifacts - Last_Read_Message
      if: steps.check-running.outputs.hasOtherRuns == 'false'
>>>>>>>+main
n: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Decrypt Telethon session file
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      env:
        API_ID:     - name: Run Telethon script
D: ${{ s    - name: Decrypt Telethon session file
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      env:
        API_ID: ${{ secrets.API_ID }}
        SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}
      run: |
        openssl aes-256-cbc -d -pbkdf2 -in "${{ secrets.API_ID }}session_name.session.enc" -out "${{ secrets.API_ID }}session_name.session" -pass pass:"${{ secrets.SESSION_PASSWORD }}"


    - name: Run Telethon script
      if: steps.check-running.outputs.hasOtherRuns == 'false'
>>>>>>>+main
D }}
        WORK_CHAT_ID: ${{ secrets.WORK_CHAT_ID }}
        PUBLIC_BOT_ID: ${{ secrets.PUBLIC_BOT_ID }}
        WAREHOUSE_CHAT_ID: ${{ secrets.WAREHOUSE_CHAT_ID }}
        LINK_CHAT_ID: ${{ secrets.LINK_CHAT_ID }}
        SETTING_CHAT_ID: ${{ secrets.SETTING_CHAT_ID }}
        SE      run: |
        python hello.py

    - name: Check if last_read_message_id.json was created
run: |
         SETTING_CHAT_ID: ${{ secrets.SETTING_CHAT_ID }}
        SETTING_THREAD_ID: ${{ secrets.SETTING_THREAD_ID }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
      run: |
        python go.py

    - name: Encrypt Telethon session file
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      env:
        API_ID: ${{ secrets.API_ID }}
        SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}
      run: |
        openssl aes-256-cbc -pbkdf2 -salt -in "${{ secrets.API_ID }}session_name.session" -out "${{ secrets.API_ID }}session_name.session.enc" -pass pass:"${{ secrets.SESSION_PASSWORD }}"

    - name: Upload session_name.enc artifact
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: session_name
        path: ${{ secrets.API_ID }}session_name.session.enc


    - name: Check if last_read_message_id.json was created
      if: steps.check-running.outputs.hasOtherRuns == 'false'
>>>>>>>+main
eated."
        fi

    - name: Upload last_read_message_id.json artifact
      if: steps.check-running.outputs.hasOtherRuns == 
    - name: Upload last_read_message_id.json artifact
th:
        - name: Upload last_read_message_id.json artifact
      if: steps.check-running.outputs.hasOtherRuns == 'false'
>>>>>>>+main
orkflow runs
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      uses: actions/github-script@v6
      with:    

        
>>>>>>>-HEAD
ecrets.PERSONAL_ACCESS_TOKEN }}  # 使用个人访问令牌
        script: |
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml',  // 使用 main.yml 作为 workflow_id
            per_page: 100,  // 获取最多100个运行
          });

          console.log('Found workflow runs:', runs.data.workflow_runs.length);

          const runIdsToDelete = runs.data.workflow_runs.slice(4).map(run => run.id);

          for (const runId of runIdsToDelete) {
            await github.rest.actions.deleteWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            console.log(`Deleted workflow run with ID: ${runId}`);
          }

    - name: Trigger Next Run
      if: steps.check-running.outputs.hasOtherRuns == 'false'
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
        -d '{"ref":"main"}'
>>>>>>> main
