name: ronin-sync

on: 
  push:
  schedule:
    - cron: "15 4,5 * * *"    # Every 3 hours at 0005, 0605, 1205, 1805

jobs:
  ronin-sync:
    runs-on: ubuntu-latest  # Use a suitable runner for your workflow 
    steps:

    - uses: actions/checkout@v3  
      with:
        ref: updev
    - name: Sync with upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1  
      with:
        target_sync_branch: main
        upstream_sync_repo: little2/ronin
        upstream_sync_branch: main 
